package com.github.mmrsic.idea.plugins.tibasic.lexer

import com.github.mmrsic.idea.plugins.tibasic.lang.TiBasicLanguage
import com.intellij.psi.tree.IElementType

object TiBasicTokenTypes {
    val LINE_NUMBER = TiBasicElementType("LINE_NUMBER")
    val PRINT_KEYWORD = TiBasicElementType("PRINT_KEYWORD")
    val LINE_NUMBER_LIST_KEYWORD = TiBasicElementType("LINE_NUMBER_LIST_KEYWORD")
    val DELETE_KEYWORD = TiBasicElementType("DELETE_KEYWORD")
    val REM_KEYWORD = TiBasicElementType("REM_KEYWORD")
    val LET_KEYWORD = TiBasicElementType("LET_KEYWORD")
    val END_KEYWORD = TiBasicElementType("END_KEYWORD")
    val STOP_KEYWORD = TiBasicElementType("STOP_KEYWORD")
    val GOTO_KEYWORD = TiBasicElementType("GOTO_KEYWORD")
    val ON_KEYWORD = TiBasicElementType("ON_KEYWORD")
    val IF_KEYWORD = TiBasicElementType("IF_KEYWORD")
    val THEN_KEYWORD = TiBasicElementType("THEN_KEYWORD")
    val ELSE_KEYWORD = TiBasicElementType("ELSE_KEYWORD")
    val FOR_KEYWORD = TiBasicElementType("FOR_KEYWORD")
    val NEXT_KEYWORD = TiBasicElementType("NEXT_KEYWORD")
    val TO_KEYWORD = TiBasicElementType("TO_KEYWORD")
    val STEP_KEYWORD = TiBasicElementType("STEP_KEYWORD")
    val REM_TEXT = TiBasicElementType("REM_TEXT")
    val UNKNOWN_STATEMENT_TEXT = TiBasicElementType("UNKNOWN_STATEMENT_TEXT")
    val NO_LINE_NUMBER_TEXT = TiBasicElementType("NO_LINE_NUMBER_TEXT")
    val PRINT_ARGUMENT = TiBasicElementType("PRINT_ARGUMENT")
    val STRING_LITERAL = TiBasicElementType("STRING_LITERAL")
    val STRING_VARIABLE = TiBasicElementType("STRING_VARIABLE")
    val NUMERIC_LITERAL = TiBasicElementType("NUMERIC_LITERAL")
    val NUMERIC_VARIABLE = TiBasicElementType("NUMERIC_VARIABLE")
    val INVALID_VARIABLE_NAME = TiBasicElementType("INVALID_VARIABLE_NAME")
    val CONCAT_OP = TiBasicElementType("CONCAT_OP")
    val PLUS_OP = TiBasicElementType("PLUS_OP")
    val MINUS_OP = TiBasicElementType("MINUS_OP")
    val MUL_OP = TiBasicElementType("MUL_OP")
    val DIV_OP = TiBasicElementType("DIV_OP")
    val POW_OP = TiBasicElementType("POW_OP")
    val EQ_OP = TiBasicElementType("EQ_OP")
    val LT_OP = TiBasicElementType("LT_OP")
    val GT_OP = TiBasicElementType("GT_OP")
    val NEQ_OP = TiBasicElementType("NEQ_OP")
    val LE_OP = TiBasicElementType("LE_OP")
    val GE_OP = TiBasicElementType("GE_OP")
    val LPAREN = TiBasicElementType("LPAREN")
    val RPAREN = TiBasicElementType("RPAREN")
    val COMMA = TiBasicElementType("COMMA")
    val COLON = TiBasicElementType("COLON")
    val SEMICOLON = TiBasicElementType("SEMICOLON")

    val PRINT_SEPARATORS = setOf(COLON, SEMICOLON, COMMA)
    val INPUT_KEYWORD = TiBasicElementType("INPUT_KEYWORD")
    val READ_KEYWORD = TiBasicElementType("READ_KEYWORD")
    val DATA_KEYWORD = TiBasicElementType("DATA_KEYWORD")
    val RESTORE_KEYWORD = TiBasicElementType("RESTORE_KEYWORD")
    val TAB_KEYWORD = TiBasicElementType("TAB_KEYWORD")
    val DISPLAY_KEYWORD = TiBasicElementType("DISPLAY_KEYWORD")
    val CALL_KEYWORD = TiBasicElementType("CALL_KEYWORD")
    val CALL_SUBPROGRAM_NAME = TiBasicElementType("CALL_SUBPROGRAM_NAME")
    val NUMERIC_FUNCTION_KEYWORD = TiBasicElementType("NUMERIC_FUNCTION_KEYWORD")
    val STRING_FUNCTION_KEYWORD = TiBasicElementType("STRING_FUNCTION_KEYWORD")
    val RANDOMIZE_KEYWORD = TiBasicElementType("RANDOMIZE_KEYWORD")
    val DEF_KEYWORD = TiBasicElementType("DEF_KEYWORD")
    val DIM_KEYWORD = TiBasicElementType("DIM_KEYWORD")
    val OPTION_BASE_KEYWORD = TiBasicElementType("OPTION_BASE_KEYWORD")
    val GOSUB_KEYWORD = TiBasicElementType("GOSUB_KEYWORD")
    val RETURN_KEYWORD = TiBasicElementType("RETURN_KEYWORD")
    val HASH = TiBasicElementType("HASH")
    val OPEN_KEYWORD = TiBasicElementType("OPEN_KEYWORD")
    val CLOSE_KEYWORD = TiBasicElementType("CLOSE_KEYWORD")
    val SEQUENTIAL_KEYWORD = TiBasicElementType("SEQUENTIAL_KEYWORD")
    val RELATIVE_KEYWORD = TiBasicElementType("RELATIVE_KEYWORD")
    val INTERNAL_KEYWORD = TiBasicElementType("INTERNAL_KEYWORD")
    val OUTPUT_KEYWORD = TiBasicElementType("OUTPUT_KEYWORD")
    val APPEND_KEYWORD = TiBasicElementType("APPEND_KEYWORD")
    val UPDATE_KEYWORD = TiBasicElementType("UPDATE_KEYWORD")
    val FIXED_KEYWORD = TiBasicElementType("FIXED_KEYWORD")
    val VARIABLE_KEYWORD = TiBasicElementType("VARIABLE_KEYWORD")
    val PERMANENT_KEYWORD = TiBasicElementType("PERMANENT_KEYWORD")

    val OPEN_ORGANIZATION_KEYWORDS = setOf(SEQUENTIAL_KEYWORD, RELATIVE_KEYWORD)
    val OPEN_FILE_TYPE_KEYWORDS = setOf(DISPLAY_KEYWORD, INTERNAL_KEYWORD)
    val OPEN_MODE_KEYWORDS = setOf(INPUT_KEYWORD, OUTPUT_KEYWORD, APPEND_KEYWORD, UPDATE_KEYWORD)
    val OPEN_RECORD_FORMAT_KEYWORDS = setOf(FIXED_KEYWORD, VARIABLE_KEYWORD)
    val OPEN_LIFETIME_KEYWORDS = setOf(PERMANENT_KEYWORD)
    val OPEN_OPTION_KEYWORDS = OPEN_ORGANIZATION_KEYWORDS + OPEN_FILE_TYPE_KEYWORDS +
        OPEN_MODE_KEYWORDS + OPEN_RECORD_FORMAT_KEYWORDS + OPEN_LIFETIME_KEYWORDS
}

class TiBasicElementType(debugName: String) : IElementType(debugName, TiBasicLanguage)
